spring.application.name=ingressos-quintal-do-farol
spring.datasource.url=jdbc:postgresql://localhost:5432/ingressos_bar
spring.datasource.username=postgres
spring.datasource.password=doJota@9@
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
